#!/usr/bin/env bash
set -e  # Exit immediately if a command exits with a non-zero status

echo "Starting Localstack daemon"
localstack start -d
echo "Waiting for LocalStack startup..."
localstack wait -t 30 || exit 1
echo "Startup complete"

echo "Creating a new ECR repository locally"
repoUri=$(awslocal ecr create-repository --repository-name repo1 | jq -r '.repository.repositoryUri')

if [ "$repoUri" != "" ]; then
    echo -e "Repo URI: $repoUri"

    echo "Building the Docker image, pushing it to local ECR URL: $repoUri"
    sleep 3
    export REPO_URI="$repoUri"
    docker compose build nardo || exit 1 # Exit if Docker Compose build fails.
    docker ps
    sleep 5
    docker compose push nardo
    docker rmi "$REPO_URI"
else
    echo -e "\033[1;33mFailed to create a new ECR repository locally \033[0m\n"
    exit 1
fi

echo "Creating ECS infrastructure locally"
awslocal cloudformation create-stack --stack-name infra --template-body file://infra/private.vpc.yml
awslocal cloudformation wait stack-create-complete --stack-name infra

echo "Deploying ECS app to local environment"
awslocal cloudformation create-stack --stack-name nardo \
    --template-body file://infra/private.nardo.yml \
    --parameters ParameterKey=ImageUrl,ParameterValue=$repoUri
awslocal cloudformation wait stack-create-complete --stack-name nardo

echo "ECS app successfully deployed. Trying to access app endpoint."
clusters=$(awslocal ecs list-clusters)
echo -e "\nClusters: $clusters\n"

cluster_arn=$(echo $clusters | jq -r '.clusterArns[0]')
# echo -e "Cluster arn: $cluster_arn\n"

## Get cluster tasks
for i in {1..5}; do
    tasks=$(awslocal ecs list-tasks --cluster $cluster_arn)
    echo -e "Tasks: $tasks\n"
    task_arn=$(echo $tasks | jq -r '.taskArns[0]')
    if [ "$task_arn" == "null" ]; then
        echo -e "\033[1;33mNo task found \033[0m\n"
        exit 1
    fi
    if [ "$task_arn" != "null" ]; then
        break
    fi
    sleep 2
done
# echo -e "Task arn: $task_arn\n"

## Get task ports
for i in {1..5}; do
    app=$(awslocal ecs describe-tasks --cluster $cluster_arn --tasks $task_arn)
    echo -e "App: $app\n"
    app_port=$(echo $app | jq -r '.tasks[0].containers[0].networkBindings[0].hostPort')
    if [ "$app_port" == "" ]; then
        echo -e "\033[1;33mNo application found \033[0m\n"
        exit 1
    fi
    if [ "$app_port" != "null" ]; then
        break
    fi
    sleep 2
done

# Get tables
tables=$(awslocal dynamodb list-tables)
echo -e "Tables: $tables\n"

# Add mock records
echo -e "Adding Mock Records"
awslocal dynamodb put-item --table-name analysisTypes --item '{"Name": {"S": "Rolling Mean"}}'
awslocal dynamodb put-item --table-name analysisTypes --item '{"Name": {"S": "Rolling Std Deviation"}}'
awslocal dynamodb put-item --table-name analysisTypes --item '{"Name": {"S": "Autocorrelation"}}'

# Get queues
queues=$(awslocal sqs list-queues)
echo -e "Queues: $queues\n"

echo -e "Curling localhost:$app_port\n"
curl localhost:$app_port

echo -e "\n\nApp successfully deployed to http://localhost:$app_port"

awslocal dynamodb batch-write-item --request-items file://./infra/useCases/mockUseCasesBatchCommand.json