#!/usr/bin/env bash

echo "Current Docker Containers:"
docker ps

# Filter and kill LocalStack containers
echo -e "\nKilling and Removing LocalStack Main Container..."
docker ps -q --filter "name=localstack-main" | xargs -r docker stop
docker ps -aq --filter "name=localstack-main" | xargs -r docker rm

echo -e "\nKilling and Removing LocalStack Pro Container..."
docker ps -q --filter "ancestor=localstack/localstack-pro" | xargs -r docker stop
docker ps -aq --filter "ancestor=localstack/localstack-pro" | xargs -r docker rm

# Filter and kill LocalStack spawned containers
echo -e "\nKilling and Removing LocalStack Spawned Containers..."
docker ps -q --filter "ancestor=localhost.localstack.cloud:4510/repo1" | xargs -r docker stop
docker ps -aq --filter "ancestor=localhost.localstack.cloud:4510/repo1" | xargs -r docker rm

echo -e "\nLocalStack containers have been stopped and removed."
