#!/usr/bin/env bash

echo "Current Docker Containers:"
docker ps

# Filter and kill LocalStack containers
echo "Killing and Removing LocalStack Main Container..."
docker ps -q --filter "name=localstack_main" | xargs -r docker stop
docker ps -aq --filter "name=localstack_main" | xargs -r docker rm

# Filter and kill LocalStack spawned containers
echo "Killing and Removing LocalStack Spawned Containers..."
docker ps -q --filter "ancestor=localhost.localstack.cloud:4510/repo1" | xargs -r docker stop
docker ps -aq --filter "ancestor=localhost.localstack.cloud:4510/repo1" | xargs -r docker rm

echo "LocalStack containers have been stopped and removed."
